# Generated by Django 4.1.5 on 2023-02-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_staff",
            field=models.BooleanField(default=True),
        ),
    ]
