# Generated by Django 4.1.5 on 2023-02-02 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_task_is_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="is_staff",
        ),
    ]
